export interface ListaTransmissao {
    id? : string;
    createAt? : number;
    nome ?: string;
    contatoListaUid?: string;
    situacao?: number ;
    libWpp?: boolean;
    libSms?: boolean;
    libEmail?: boolean;
    mensagem?: string;
    anexo?: string;
    acao?: string;
    disparoImediato?: boolean;
    agdDom?:boolean;
    agdHrDom?:string;
    agdSeg?:boolean;
    agdHrSeg?:string;
    agdTer?:boolean;
    agdHrTer?:string;
    agdQua?:boolean;
    agdHrQua?:string;
    agdQui?:boolean;
    agdHrQui?:string;
    agdSex?:boolean;
    agdHrSex?:string;
    agdSab?:boolean;
    agdHrSab?:string;
    alcanceEmail?:number;
    alcanceEmailAguardando?:number;
    alcanceEmailEnviado?:number;
    alcanceEmailErro?:number;
    alcanceEmailVisualizado?:number;
    alcanceSms?:number;
    alcanceSmsAguardando?:number;
    alcanceSmsEnviado?:number;
    alcanceSmsErro?:number;
    alcanceSmsVisualizado?:number;
    alcanceWpp?:number;
    alcanceWppAguardando?:number;
    alcanceWppEnviado?:number;
    alcanceWppErro?:number;
    alcanceWppVisualizado?:number;
    usuarioUid?:string;
    usuarioNome?:string;
    cidade?:string;
    estado?:string;
    grupo?:string;
    subgrupo?:string;
    canalFiltro?:string;
    wppTotal?:number;
    smsTotal?:number;
    emailTotal?:number;
    wppAguardando?:number;
    wppEnviado?:number;
    wppVisualizado?:number;
    wppErro?:number;
    smsAguardando?:number;
    smsEnviado?:number;
    smsVisualizado?:number;
    smsErro?:number;
    emailAguardando?:number;
    emailEnviado?:number;
    emailVisualizado?:number;
    emailErro?:number;
};

export interface ListaTransmissaoDisparos {
    id?:string;
    createAt?:number;
    sitWppMsg?:boolean;
    sitWppAnexo?:boolean;
    sitWppAcao?:boolean;
    sitEmail?:boolean;
    sitSms?:boolean;
    tipoEnvio?:string;
    destino?:string;
    nome?:string;
    listaUid?:string;
    errorMsg?:string;
    wppAguardando?:boolean;
    wppEnviado?:boolean;
    wppVisualizado?:boolean;
    wppErro?:boolean;
    smsAguardando?:boolean;
    smsEnviado?:boolean;
    smsVisualizado?:boolean;
    smsErro?:boolean;
    emailAguardando?:boolean;
    emailEnviado?:boolean;
    emailVisualizado?:boolean;
    emailErro?:boolean;
};